/**
 * A few dishes from each country, offered as a starting point.
 *
 * WHY THIS FILE EXISTS. The fil rouge can hand a table a country nobody at it
 * has ever cooked from — the draw is honest, so some weeks are Tuvalu and
 * Liechtenstein rather than Italy and Mexico. A theme you cannot begin is not
 * a constraint, it is a dead end, and three names are enough to turn one into
 * the other.
 *
 * THEY ARE NOT "THE NATIONAL DISH". Naming one is a claim, and a wrong or
 * reductive one is the kind of thing that gets screenshotted. These are *some*
 * dishes from there, the interface says so, and nothing anywhere calls them
 * official.
 *
 * THEY ARE ALSO NOT A MENU. Three suggestions, shown as suggestions: if six
 * people cook the three named dishes the fil rouge has made the evening
 * narrower rather than wider, which is the opposite of the point.
 *
 * NOT TRANSLATED, AND THAT IS NOT AN OMISSION. A dish name is a proper noun —
 * paella is paella in every language, and so is phở. Where a dish is genuinely
 * known by a translated name in French the French form is used, because this
 * app's two languages are French and English and the French reader is the one
 * more likely to be reading it.
 *
 * Keyed by ISO 3166-1 alpha-2, the same code the catalogue stores (0084).
 */
export const COUNTRY_DISHES: Record<string, string[]> = {
  FR: ['Pot-au-feu', 'Coq au vin', 'Ratatouille'],
  IT: ['Risotto alla milanese', 'Ossobuco', 'Tiramisù'],
  PT: ['Bacalhau à Brás', 'Caldo verde', 'Pastel de nata'],
  ES: ['Paella', 'Tortilla española', 'Gazpacho'],
  GR: ['Moussaka', 'Souvlaki', 'Spanakopita'],
  CY: ['Halloumi grillé', 'Souvla', 'Kleftiko'],
  MT: ['Pastizzi', 'Fenkata (lapin)', 'Lampuki pie'],
  AD: ['Trinxat', 'Escudella', 'Cargols a la llauna'],
  MC: ['Barbagiuan', 'Socca', 'Fougasse monégasque'],
  SM: ['Torta tre monti', 'Nidi di rondine', 'Bustrengo'],
  AM: ['Khorovats', 'Dolma', 'Lavash'],
  BA: ['Ćevapi', 'Burek', 'Bosanski lonac'],
  BG: ['Banitsa', 'Shopska salad', 'Tarator'],
  GE: ['Khachapuri', 'Khinkali', 'Satsivi'],
  MK: ['Tavče gravče', 'Ajvar', 'Pastrmajlija'],
  ME: ['Njeguški pršut', 'Kačamak', 'Priganice'],
  RO: ['Sarmale', 'Mămăligă', 'Mici'],
  RS: ['Pljeskavica', 'Sarma', 'Gibanica'],
  SI: ['Potica', 'Štruklji', 'Jota'],
  RU: ['Borscht', 'Pelmeni', 'Blini'],
  UA: ['Borshch', 'Varenyky', 'Deruny'],
  BY: ['Draniki', 'Machanka', 'Kholodnik'],
  HR: ['Peka', 'Štrukli', 'Pašticada'],
  MD: ['Mămăligă', 'Plăcinte', 'Zeamă'],
  AT: ['Wiener Schnitzel', 'Tafelspitz', 'Sachertorte'],
  BE: ['Moules-frites', 'Carbonnade flamande', 'Waterzooi'],
  CZ: ['Svíčková', 'Guláš', 'Trdelník'],
  DK: ['Smørrebrød', 'Frikadeller', 'Æbleskiver'],
  EE: ['Verivorst', 'Mulgipuder', 'Kama'],
  FI: ['Karjalanpiirakka', 'Lohikeitto', 'Ruisleipä'],
  IS: ['Plokkfiskur', 'Kjötsúpa', 'Skyr'],
  IE: ['Irish stew', 'Colcannon', 'Soda bread'],
  LV: ['Pois gris au lard', 'Rupjmaize', 'Sklandrausis'],
  LT: ['Cepelinai', 'Šaltibarščiai', 'Kugelis'],
  NL: ['Stamppot', 'Bitterballen', 'Erwtensoep'],
  NO: ['Fårikål', 'Rakfisk', 'Lefse'],
  PL: ['Pierogi', 'Bigos', 'Żurek'],
  SK: ['Bryndzové halušky', 'Kapustnica', 'Lokše'],
  SE: ['Köttbullar', 'Gravlax', 'Janssons frestelse'],
  GB: ['Roast beef & Yorkshire pudding', 'Shepherd\'s pie', 'Fish and chips'],
  HU: ['Gulyás', 'Halászlé', 'Lángos'],
  US: ['Clam chowder', 'Barbecue ribs', 'Apple pie'],
  CA: ['Tourtière', 'Poutine', 'Butter tarts'],
  NZ: ['Hāngī', 'Pavlova', 'Whitebait fritters'],
  AU: ['Meat pie', 'Lamingtons', 'Barramundi grillé'],
  CL: ['Pastel de choclo', 'Empanadas de pino', 'Curanto'],
  CH: ['Fondue', 'Rösti', 'Älplermagronen'],
  LU: ['Judd mat Gaardebounen', 'Bouneschlupp', 'Quetschentaart'],
  AR: ['Asado', 'Empanadas', 'Locro'],
  UY: ['Chivito', 'Asado', 'Torta frita'],
  IL: ['Falafel', 'Shakshuka', 'Sabich'],
  DE: ['Sauerbraten', 'Currywurst', 'Schwarzwälder Kirschtorte'],
  LI: ['Käsknöpfle', 'Ribel', 'Hafalaab'],
  SA: ['Kabsa', 'Jareesh', 'Mutabbaq'],
  OM: ['Shuwa', 'Majboos', 'Halwa omanais'],
  AE: ['Machboos', 'Harees', 'Luqaimat'],
  QA: ['Machboos', 'Thareed', 'Balaleet'],
  KW: ['Machboos', 'Murabyan', 'Gers ogaily'],
  BH: ['Machboos', 'Muhammar', 'Balaleet'],
  EG: ['Koshari', 'Ful medames', 'Molokhia'],
  PK: ['Biryani', 'Nihari', 'Haleem'],
  YE: ['Saltah', 'Mandi', 'Bint al-sahn'],
  MR: ['Méchoui', 'Couscous', 'Thieboudienne'],
  DJ: ['Skoudehkaris', 'Fah-fah', 'Lahoh'],
  MV: ['Mas huni', 'Garudhiya', 'Bis keemiya'],
  DZ: ['Couscous', 'Chorba frik', 'Rechta'],
  MA: ['Tajine', 'Couscous', 'Pastilla'],
  TN: ['Couscous', 'Brik', 'Lablabi'],
  TR: ['Kebab', 'Mantı', 'Baklava'],
  AL: ['Tavë kosi', 'Byrek', 'Fërgesë'],
  JO: ['Mansaf', 'Maqluba', 'Falafel'],
  LB: ['Tabbouleh', 'Kibbeh', 'Manakish'],
  SY: ['Kibbeh', 'Fattoush', 'Muhammara'],
  IQ: ['Masgouf', 'Dolma', 'Kubba'],
  IR: ['Chelow kabab', 'Ghormeh sabzi', 'Fesenjan'],
  LY: ['Bazin', 'Shorba libiya', 'Usban'],
  AZ: ['Plov', 'Dolma', 'Dovga'],
  AF: ['Kabuli pulao', 'Mantu', 'Ashak'],
  KG: ['Beshbarmak', 'Lagman', 'Boorsok'],
  MN: ['Buuz', 'Khuushuur', 'Tsuivan'],
  TJ: ['Qurutob', 'Osh', 'Sambusa'],
  TM: ['Palaw', 'Dograma', 'Chorek'],
  UZ: ['Plov', 'Lagman', 'Samsa'],
  KZ: ['Beshbarmak', 'Kazy', 'Baursak'],
  CN: ['Mapo tofu', 'Canard laqué', 'Jiaozi'],
  JP: ['Sushi', 'Ramen', 'Okonomiyaki'],
  KP: ['Pyongyang naengmyeon', 'Onban', 'Kimchi'],
  KR: ['Bibimbap', 'Kimchi jjigae', 'Bulgogi'],
  TW: ['Beef noodle soup', 'Gua bao', 'Omelette aux huîtres'],
  MY: ['Nasi lemak', 'Laksa', 'Rendang'],
  TL: ['Ikan sabuko', 'Batar da\'an', 'Bibinka'],
  PH: ['Adobo', 'Sinigang', 'Lechon'],
  ID: ['Nasi goreng', 'Rendang', 'Gado-gado'],
  GY: ['Pepperpot', 'Cook-up rice', 'Roti'],
  SR: ['Pom', 'Bami', 'Roti'],
  DO: ['Sancocho', 'La bandera', 'Mangú'],
  BN: ['Ambuyat', 'Nasi katok', 'Kelupis'],
  SG: ['Hainanese chicken rice', 'Chilli crab', 'Laksa'],
  TH: ['Pad thai', 'Tom yum', 'Curry vert'],
  VN: ['Phở', 'Bánh mì', 'Gỏi cuốn'],
  KH: ['Amok', 'Lok lak', 'Nom banh chok'],
  MM: ['Mohinga', 'Laphet thoke', 'Ohn no khao swè'],
  LA: ['Larb', 'Tam mak hoong', 'Khao piak sen'],
  LK: ['Rice and curry', 'Hoppers', 'Kottu'],
  IN: ['Biryani', 'Dal makhani', 'Masala dosa'],
  BD: ['Ilish bhapa', 'Bhuna khichuri', 'Pitha'],
  NP: ['Dal bhat', 'Momo', 'Sel roti'],
  BT: ['Ema datshi', 'Phaksha paa', 'Suja'],
  ZM: ['Nshima ne ifisashi', 'Kapenta', 'Chikanda'],
  ZW: ['Sadza ne nyama', 'Muriwo une dovi', 'Mazondo'],
  UG: ['Matoke', 'Luwombo', 'Rolex'],
  KE: ['Ugali', 'Nyama choma', 'Sukuma wiki'],
  BI: ['Boko boko harees', 'Isombe', 'Ubugali'],
  MW: ['Nsima', 'Chambo grillé', 'Kondowole'],
  TZ: ['Ugali', 'Nyama choma', 'Pilau de Zanzibar'],
  RW: ['Isombe', 'Ubugali', 'Brochettes'],
  CG: ['Saka-saka', 'Poulet à la moambé', 'Makemba'],
  MZ: ['Matapa', 'Frango à zambeziana', 'Xima'],
  CD: ['Poulet à la moambé', 'Fufu', 'Pondu'],
  AO: ['Muamba de galinha', 'Funge', 'Calulu'],
  CF: ['Gozo', 'Kanda ti nyma', 'Ngunza'],
  CM: ['Ndolé', 'Poulet DG', 'Eru'],
  NG: ['Jollof rice', 'Egusi soup', 'Suya'],
  TG: ['Fufu', 'Ablo', 'Djenkoumé'],
  BJ: ['Amiwo', 'Wagasi', 'Akassa'],
  GH: ['Jollof rice', 'Waakye', 'Banku et tilapia'],
  CI: ['Attiéké', 'Kedjenou', 'Alloco'],
  GN: ['Poulet yassa', 'Riz gras', 'Fouti'],
  GW: ['Caldo de mancarra', 'Chabéu', 'Jollof'],
  SL: ['Cassava leaf stew', 'Jollof rice', 'Fufu'],
  LR: ['Jollof rice', 'Palava sauce', 'Dumboy'],
  MG: ['Romazava', 'Ravitoto', 'Koba'],
  TD: ['Boule de mil', 'Daraba', 'Mouton grillé'],
  SS: ['Kisra', 'Ful', 'Asida'],
  SN: ['Thieboudienne', 'Yassa', 'Mafé'],
  ML: ['Tigadèguèna', 'Riz au gras', 'Fonio'],
  NE: ['Dambou', 'Kilishi', 'Fura'],
  BF: ['Riz gras', 'Tô', 'Poulet bicyclette'],
  SD: ['Ful medames', 'Kisra', 'Asida'],
  GM: ['Benachin', 'Domoda', 'Superkanja'],
  SO: ['Bariis iskukaris', 'Suqaar', 'Canjeero'],
  ET: ['Doro wat', 'Injera', 'Kitfo'],
  ER: ['Zigni', 'Injera', 'Tsebhi'],
  ZA: ['Bobotie', 'Braai', 'Bunny chow'],
  NA: ['Potjiekos', 'Kapana', 'Oshifima'],
  BW: ['Seswaa', 'Bogobe', 'Morogo'],
  SZ: ['Sidvudvu', 'Emasi etinkhobe', 'Siphuphe'],
  LS: ['Papa', 'Moroho', 'Likhobe'],
  BR: ['Feijoada', 'Moqueca', 'Brigadeiro'],
  MX: ['Mole poblano', 'Tacos al pastor', 'Pozole'],
  CO: ['Bandeja paisa', 'Ajiaco', 'Arepas'],
  VE: ['Pabellón criollo', 'Arepas', 'Hallacas'],
  PE: ['Ceviche', 'Lomo saltado', 'Ají de gallina'],
  BO: ['Salteñas', 'Silpancho', 'Pique macho'],
  GT: ['Pepián', 'Kak\'ik', 'Tamales'],
  EC: ['Encebollado', 'Locro de papa', 'Ceviche'],
  HN: ['Baleadas', 'Sopa de caracol', 'Plato típico'],
  SV: ['Pupusas', 'Yuca frita', 'Sopa de pata'],
  NI: ['Gallo pinto', 'Nacatamal', 'Vigorón'],
  CR: ['Gallo pinto', 'Casado', 'Olla de carne'],
  PA: ['Sancocho', 'Ropa vieja', 'Carimañolas'],
  CV: ['Cachupa', 'Pastel com o diabo dentro', 'Buzio'],
  BZ: ['Rice and beans', 'Fry jacks', 'Garnaches'],
  CU: ['Ropa vieja', 'Moros y cristianos', 'Tostones'],
  HT: ['Griot', 'Soup joumou', 'Diri ak djon djon'],
  PY: ['Sopa paraguaya', 'Chipa', 'Mbejú'],
  JM: ['Ackee and saltfish', 'Jerk chicken', 'Rice and peas'],
  TT: ['Doubles', 'Callaloo', 'Pelau'],
  BS: ['Conch salad', 'Cracked conch', 'Peas and rice'],
  BB: ['Cou-cou and flying fish', 'Pudding and souse', 'Macaroni pie'],
  LC: ['Green fig and saltfish', 'Bouyon', 'Callaloo'],
  AG: ['Fungee and pepperpot', 'Ducana', 'Saltfish'],
  VC: ['Breadfruit rôti et jackfish', 'Callaloo soup', 'Buljol'],
  GD: ['Oil down', 'Callaloo', 'Glace à la muscade'],
  SC: ['Ladob', 'Poisson grillé rougay', 'Curry de coco'],
  FJ: ['Kokoda', 'Lovo', 'Rourou'],
  MU: ['Dholl puri', 'Rougaille', 'Gâteau piment'],
  DM: ['Callaloo soup', 'Bakes', 'Titiwi accra'],
  KN: ['Goat water', 'Stewed saltfish', 'Conkies'],
  SB: ['Poi', 'Pudding de manioc', 'Poisson grillé'],
  WS: ['Palusami', 'Oka', 'Fa\'ausi'],
  KI: ['Palusami', 'Te bua toro', 'Poisson de récif grillé'],
  VU: ['Lap lap', 'Tuluk', 'Crabe de cocotier'],
  FM: ['Chukuchuk', 'Fruit à pain', 'Poisson au lait de coco'],
  KM: ['Langouste à la vanille', 'Mkatra foutra', 'Pilaou'],
  PG: ['Mumu', 'Kaukau', 'Crêpes de sagou'],
  MH: ['Poisson de récif grillé', 'Fruit à pain', 'Riz au coco'],
  NR: ['Poisson au coco', 'Pandanus', 'Thon grillé'],
  PW: ['Tinola', 'Taro', 'Poisson grillé'],
  TO: ['\'Ota \'ika', 'Lu pulu', 'Faikakai'],
  TV: ['Pulaka', 'Poisson au coco', 'Fekei'],
  GA: ['Poulet nyembwe', 'Odika', 'Bâton de manioc'],
  ST: ['Calulu de peixe', 'Blablá', 'Angu'],
  GQ: ['Pepesup', 'Sopa de cacahuete', 'Yuca con pescado'],
}

/** The dishes for a country, or an empty list where none are written yet — the
 *  interface shows nothing rather than an empty heading. */
export function dishesFor(code: string): string[] {
  return COUNTRY_DISHES[code] ?? []
}
